// Distance
const MAX_DISTANCE_ALLOWED = 100 // meters
const MAX_DISTANCE_VIEW_GYM_ALLOWED = 10 // km

// Time
const DISTANCE_IN_MINUTES_FROM_CHECK_IN_CREATION_ALLOWED = 20

export {
  MAX_DISTANCE_ALLOWED,
  MAX_DISTANCE_VIEW_GYM_ALLOWED,
  DISTANCE_IN_MINUTES_FROM_CHECK_IN_CREATION_ALLOWED,
}
